name: 'marketo_source_integration_tests'
version: '0.8.0'
profile: 'integration_tests'
config-version: 2

vars:
    marketo_source:
        marketo__enable_campaigns:   true      # Un-comment line to enable testing the campaigns table
        marketo__enable_programs:    true      # Un-comment line to enable testing the programs table
        marketo_lead_identifier: "lead"
        marketo_lead_describe_identifier: "lead_describe"
        marketo_activity_change_data_value_identifier: "activity_change_data_value"
        marketo_campaign_identifier: "campaign"
        marketo_program_identifier: "program"
        marketo_email_template_history_identifier: "email_template_history"
        marketo_activity_click_email_identifier: "activity_click_email"
        marketo_activity_email_delivered_identifier: "activity_email_delivered"
        marketo_activity_email_bounced_identifier: "activity_email_bounced"
        marketo_activity_open_email_identifier: "activity_open_email"
        marketo_activity_unsubscribe_email_identifier: "activity_unsubscribe_email"
        marketo_activity_send_email_identifier: "activity_send_email"
        marketo_activity_delete_lead_identifier: "activity_delete_lead"
        marketo_activity_merge_leads_identifier: "activity_merge_leads"